name: subway_stations
description: Flutter application which represents Minsk subway stations in different ways
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  transparent_image: ^0.1.0
  cloud_firestore: ^0.7.4
  geolocator: ^2.1.1
  tuple: ^1.0.2
  simple_permissions: ^0.1.9
  haversine: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
